on:
  push:
    branches:
      - master
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@3.0.0
        with:
          ftp-server: sftp://ns3044267.siegler-informatique.fr:61212/var/www/thivinfo.com/test-deploy
          ftp-username: sebastienserre
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          git-ftp-args: --insecure --key ${{ secrets.PUBKEY }}