name: Staging Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./themes/our-awesome-theme
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: FTP Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          ftp-server: sftp://ns3044267.siegler-informatique.fr:61212/
          ftp-username: sebastienserre
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./deploy/