on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ns3044267.siegler-informatique.fr
          PORT: 10021
          FTP_USERNAME: sebastienserre
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          REMOTE_DIR: /var/www/thivinfo.com/test-deploy