name: Staging Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          fetch-depth: 2
      - name: FTP Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ns3044267.siegler-informatique.fr
          port: 10021
          username: sebastienserre
          password: ${{ secrets.FTP_PASSWORD }}