name: Deploy via git-ftp
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "$SSH_PPK" > the_key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: git-ftp push
        uses: hrsetyono/git-sftp-action@v4
        with:
          url: "sftp://ns3044267.siegler-informatique.fr"
          user: ${{ secrets.SSH_PRIVATE_KEY }}
          options: "--key /the_key --auto-init --remote-root /var/www/thivinfo.com/test-deploy/"